### ISSUE TITLE
Pyramid of doom

### ISSUE THREAD

**Issue by miklebel** [Ranky1ne/VorGor#2]
https://github.com/Ranky1ne/VorGor/blob/e0bafb5b174e96c4df332f1f3e2b3d05ebdce602/app.js#L31

![image](https://user-images.githubusercontent.com/60480636/183567569-eda72c25-51f6-483e-a77a-b1c3685051c3.png)

Чтобы избежать Pyramid of doom воспользуйся функцией, что я тебе дал, и получай с нее данные асинхронно.

**Comment by Ranky1ne** [comment]
Ты про пормис или про скуиз

**Comment by Ranky1ne** [comment]
const query = (connection, query, args) => {
		return new Promise((resolve, reject) => {
		  connection.query(query, args, (err, res) => {
			if (err) reject  (err);
			if (err === null){
				dott = res.insertId;
			}
			resolve(dott)
			});
		});
	  };

	  try {
		await query(
			connection,
			"INSERT INTO `nodelogin`.`newForm` ( `Заказчик`, `Перевозчик`, `Объем`, `Сырье`, `и тд.`) VALUES (?, ?, ?, ?, ?); ",
			[customer, carrier, volume, rawMaterial, etc]
		).then((dott)=>{
			query(
				connection,
				 "INSERT INTO cars (`Заказчик`, `Перевозчик`, `orderId`) VALUES (?, ?, ?)",
				  [customer, carrier, dott]
			)
		});
	  } catch (error) {
	 console.log(error)
	  }

смотри, у меня вопрос почему reject в первом цикле не выкидывает эррор если введешь больше 250 знаков, а выкидывает то, что Cannot read properties of undefined (reading 'insertId'). Те получается он не выкидывает ее по середине функции или как?

**Comment by miklebel** [comment]
> смотри, у меня вопрос почему reject в первом цикле не выкидывает эррор если введешь больше 250 знаков, а выкидывает то, что Cannot read properties of undefined (reading 'insertId'). Те получается он не выкидывает ее по середине функции или как?

Ничего не понятно, убери `.then`. Сделай так:

```
try {
     const response = await query(...)
     await query(..., response,...)
```
